name: BelvensArenas
main: belven.arena.ArenaManager
version: 1
depend: [WorldEdit, BelvensResources]

commands: 
   ba:
      description: Spawns mobs in an arena
      usage: /ba warp(w for short)  <ArenaName> , /ba leave(l for short)
      permission: BelvensArenas.ba
      permission-message: You don't have permission to do this